Fixed handling of space manager teams
OctopusDeployLabs/terraform-provider-octopusdeploy pull request #307
Opened 2022-01-11 08:20 UTC by slewis74

This PR updates the Space schema for Terraform to hide the special Space Managers team from the state file. This team should be an Octopus internal concern, but while it's being returned from the API the easiest option we have for now is to remove it on read and add it back in on updates.

Fixes #306

2022-01-11 10:33 UTC, domenicsim1 approved these changes
We should make sure our naming convention is consistent. Currently I see sometimes use ‘myId’ and other times ‘myID’. I recommend capitalising ID in all cases as it seems to be more common with what is standard to Go.

Otherwise LGTM! 👍🏻

2022-01-12 00:09 UTC, slewis74 commented
You meaning `spaceManagersTeamIdPrefix` might be better as `spaceManagersTeamIDPrefix`?

2022-01-12 00:16 UTC, domenicsim1 commented
> You meaning `spaceManagersTeamIdPrefix` might be better as `spaceManagersTeamIDPrefix`?

Yes,` spaceManagersTeamIdPrefix` might be better as `spaceManagersTeamIDPrefix`.
Same for `teamIds` might be batter as `teamIDs`.
As you can see:
```
func addSpaceManagers(spaceID string, teamIds []string) []string {
```
Looks inconstant having `spaceID` with id capital and teamIds without.

2022-01-12 01:21 UTC, domenicsim1 requested changes

2022-01-12 01:21 UTC, domenicsim1 commented on octopusdeploy/schema_space.go
> +func removeSpaceManagers(teamIds []string) []string {
Missed this one

2022-01-12 04:24 UTC, domenicsim1 approved these changes

2022-01-12 04:24 UTC, domenicsim1 approved these changes

2022-01-12 04:25 UTC, merged