feat: Support process scoped variables
OctopusDeployLabs/terraform-provider-octopusdeploy pull request #593
Opened 2024-01-09 05:31 UTC by tleed5

[SC-66829]
Based on https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/pull/562 

# Result
- Updated `go-octopusdeploy` version to include the changes that allow for process scope variable matching (see https://github.com/OctopusDeploy/go-octopusdeploy/pull/230)
- Add `process` to variable scope schema to allow it to be used in terraform. 

# Example 
```
resource "octopusdeploy_variable" "test_variable" {
  owner_id  = "Projects-21"
  type      = "String"
  name      = "Test Process Scope"
  value     = "Scopey"
  scope {
    processes = ["Runbooks-1"]
  }
}
```

fixes #361

2024-01-09 09:30 UTC, zentron requested changes
Looks reasonable. If we can add (or update an existing) test to include the usage of this parameter would be nice.

2024-01-11 00:16 UTC, tleed5 commented on terraform/49-variables/variables.tf
Tenant scoped variables are already been tested [here](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/blob/78410f278967836377b4cb6fd361961abde38116/terraform/26-tenant_variables/tenant_variables.tf) so it didn't seem necessary to test them again

2024-01-11 00:30 UTC, tleed5 commented on integration_test.go
> +		}
I figure we can assert test that the correct amount of variables are created, anything else would be covered by the fact the variable resources are created correctly.

2024-01-11 00:59 UTC, zentron approved these changes
Apart from maybe a quick tweak to the test to validate that the scope exists as expected, even just explicitly checking some known value for each differently scoped variable then feel free to merge.
🙇 Thanks for pushing this one forward

2024-01-11 01:37 UTC, merged