chore!: migrate project resource & datasource
OctopusDeployLabs/terraform-provider-octopusdeploy pull request #689
Opened 2024-07-24 14:18 UTC by HuyPhanNguyen

Migration for project resource and data source
[sc-84548](https://app.shortcut.com/octopusdeploy/story/84548/projects-data-source)
[sc-84172](https://app.shortcut.com/octopusdeploy/story/84172/project-resource)

2024-08-02 04:34 UTC, hnrkndrssn requested changes
A question about the return values from one of the new functions, and some comments about comments

2024-08-02 04:34 UTC, hnrkndrssn commented on octopusdeploy_framework/resource_project.go
> +	// Password doesn't return from API so this is work around
Not sure what this comment is referring to...is it still necessary?

2024-08-02 04:34 UTC, hnrkndrssn commented on octopusdeploy_framework/resource_project.go
> +	// Update the state with the deployment settings
Looks like this should be a few lines up

2024-08-02 04:34 UTC, hnrkndrssn commented on octopusdeploy_framework/resource_project_flatten.go
> +func processPersistenceSettings(ctx context.Context, project *projects.Project, model *projectResourceModel, diags diag.Diagnostics) (diag.Diagnostics, *projectResourceModel, diag.Diagnostics, bool)
There's two diagnostics return values, is that intentional?

2024-08-02 04:34 UTC, hnrkndrssn commented on octopusdeploy_framework/resource_project_flatten.go
> +func processPersistenceSettings(ctx context.Context, project *projects.Project, model *projectResourceModel, diags diag.Diagnostics) (diag.Diagnostics, *projectResourceModel, diag.Diagnostics, bool)
And what is the boolean supposed to be about?

2024-08-05 00:38 UTC, benPearce1 commented on octopusdeploy_framework/schemas/project.go
> +			"template": resourceSchema.ListNestedBlock{
Got some errors when setting up templates:
```
template {
    name = "template"
  }
```

>│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to octopusdeploy_project.project, provider "provider[\"octopus.com/com/octopusdeploy\"]" produced an unexpected new value: .template[0].label: was
│ null, but now cty.StringVal("").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to octopusdeploy_project.project, provider "provider[\"octopus.com/com/octopusdeploy\"]" produced an unexpected new value:
│ .template[0].display_settings: was null, but now cty.MapValEmpty(cty.String).
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

2024-08-05 01:09 UTC, benPearce1 approved these changes
Some issues discovered with variable template state, other than it looks good.

2024-08-05 08:04 UTC, merged