Isaac/tenant resource
OctopusDeployLabs/terraform-provider-octopusdeploy pull request #707
Opened 2024-08-01 02:15 UTC by IsaacCalligeros95

2024-08-02 02:40 UTC, IsaacCalligeros95 commented on octopusdeploy_framework/resource_tenant.go
> +	sort.Strings(tenant.TenantTags)
These sorts are a little odd, but I was receiving inconsistent input/output and this seems like the only viable fix.
![image](https://github.com/user-attachments/assets/926ae949-59f5-4777-b81c-83213b5ee05a)

2024-08-07 04:31 UTC, hnrkndrssn commented on docs/resources/tenant.md
> +
Description missing from schema

2024-08-07 04:37 UTC, hnrkndrssn commented on octopusdeploy_framework/resource_tenant.go
> +	if err != nil {
You'll run into the same thing I just ran into with the runbook resource, if a tenant is deleted from Octopus next time you run plan/apply you'll get an error as Terraform can't find the resource. I realised that `errors.ProcessApiErrors` removes the resource from state if the response from the API is a 404.

2024-08-07 05:10 UTC, hnrkndrssn requested changes
Looks mostly good, just a note about that we need to remove resources that have been deleted in Octopus from state, otherwise customers will get errors when trying to execute terraform.

2024-08-08 01:54 UTC, IsaacCalligeros95 commented on docs/data-sources/azure_cloud_service_deployment_targets.md
> -- `endpoint` (List of Object) (see [below for nested schema](#nestedatt--azure_cloud_service_deployment_targets--endpoint))
These changes are a result of the Optional -> Computed changes in [this PR](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/commit/3a8a027a764cda034b8840bbba6df254e5f0d6b4).

2024-08-12 03:47 UTC, hnrkndrssn approved these changes

2024-08-12 03:57 UTC, merged