Chore!: Migrate tentacle certificate
OctopusDeployLabs/terraform-provider-octopusdeploy pull request #716
Opened 2024-08-06 04:50 UTC by IsaacCalligeros95

Migrates the tentacle Certificate resource

2024-08-07 06:27 UTC, hnrkndrssn commented on octopusdeploy_framework/schemas/schema_tentacle_certificate.go
> +		Description: "Manages a tentacle certificate in Octopus Deploy.",
```suggestion
		Description: "Generates a X.509 self-signed certificate for use with a Octopus Deploy Tentacle.",
```

2024-08-07 06:30 UTC, hnrkndrssn commented on octopusdeploy_framework/schemas/schema_tentacle_certificate.go
> +			"id": util.GetIdResourceSchema(),
This should be read-only

2024-08-07 06:32 UTC, hnrkndrssn commented on octopusdeploy_framework/util/random.go
> +package util
Can we move this to `internal` and use it in both `octopusdeploy` and `octopusdeploy_framework` so we don't have to maintain duplicate code.

2024-08-07 06:33 UTC, hnrkndrssn requested changes
Looks good, just a few minor things to make future-us a bit happier

2024-08-12 05:43 UTC, benPearce1 approved these changes
LGTM. Tested locally, managed to generate a cert with sensitive values, including being updated due to a changed attribute on a dependent resource

2024-08-12 05:43 UTC, hnrkndrssn approved these changes

2024-08-12 05:46 UTC, merged