chore!: Migrate username_password_account resource
OctopusDeployLabs/terraform-provider-octopusdeploy pull request #721
Opened 2024-08-08 04:44 UTC by HuyPhanNguyen

2024-08-08 05:58 UTC, hnrkndrssn requested changes
We've got a new way to handle a missing resource in the `Read` function, please rebase `main` and change the error condition in `Read`.

Other than that the changes look good, just a minor docs update.

2024-08-08 05:58 UTC, hnrkndrssn commented on octopusdeploy_framework/schemas/username_password_account.go
> +			"description":                       util.ResourceString().Optional().Computed().PlanModifiers(stringplanmodifier.UseStateForUnknown()).Default("").Description("The description of this username/pa
```suggestion
			"description":                       util.ResourceString().Optional().Computed().PlanModifiers(stringplanmodifier.UseStateForUnknown()).Default("").Description("The description of this username/password account.").Build(),
```

2024-08-12 04:52 UTC, benPearce1 approved these changes
LGTM. Tested locally for migration, create, update, destroy and import.

2024-08-12 04:55 UTC, hnrkndrssn approved these changes

2024-08-12 05:00 UTC, merged