chore: update README for framework migration
OctopusDeployLabs/terraform-provider-octopusdeploy pull request #813
Opened 2024-11-13 23:14 UTC by domenicsim1

2024-11-13 23:24 UTC, mjhilton requested changes
I have ideas for a larger rework of these files, but I think this is a useful addition for now. Just want the Conventional Commits doco linked so people can easily figure out what that means if not already exposed to it.

2024-11-13 23:24 UTC, mjhilton commented on CONTRIBUTING.md
> +This project is built, tested, and released by workflows defined in GitHub Actions (see [Actions](/actions/) for more information). Release management is controlled through [Release-Please](https://g
```suggestion
This project is built, tested, and released by workflows defined in GitHub Actions (see [Actions](/actions/) for more information). Release management is controlled through [Release-Please](https://github.com/googleapis/release-please). 

Please use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary), and choose the "Squash and Merge" option to merge your PR (so we get a nice, clear Git history that makes it obvious what's changed)
```

2024-11-14 00:08 UTC, mjhilton approved these changes

2024-11-14 05:24 UTC, mattocto commented
LGTM, thank you.

2024-11-14 05:24 UTC, mattocto approved these changes

2024-11-14 21:57 UTC, merged