feat: support deployment freeze recurring schedule
OctopusDeployLabs/terraform-provider-octopusdeploy pull request #840
Opened 2024-12-08 23:20 UTC by HuyPhanNguyen

- Deployment freeze support recurring schedule
- Deployment freeze data source support retrieves recurring schedule
- Deployment freeze data source support retrieves tenant scopes
- Add test for deployment freeze data source
- Add validation for recurring schedule 

[sc-99172](https://app.shortcut.com/octopusdeploy/story/99172/terraform-support-recurring-schedule)

```
resource "octopusdeploy_deployment_freeze" "test_freeze" {
    name  = "Test Recurring Freeze"
    start = "2025-12-09T01:47:00Z"
    end   = "2025-12-10T01:47:00Z"
    
    recurring_schedule = {
        type = "DaysPerWeek"
        unit = 24
        end_type = "AfterOccurrences"
        end_after_occurrences = 5
        days_of_week = ["Monday", "Wednesday", "Friday"]
    }

    # depends_on = [octopusdeploy_space.test_space]
}
```

## Create
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # octopusdeploy_deployment_freeze.test_freeze will be created
  + resource "octopusdeploy_deployment_freeze" "test_freeze" {
      + end                = "2025-12-10T01:47:00Z"
      + id                 = (known after apply)
      + name               = "Test Recurring Freeze"
      + recurring_schedule = {
          + days_of_week          = [
              + "Monday",
              + "Wednesday",
              + "Friday",
            ]
          + end_after_occurrences = 5
          + end_type              = "AfterOccurrences"
          + type                  = "DaysPerWeek"
          + unit                  = 24
        }
      + start              = "2025-12-09T01:47:00Z"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

octopusdeploy_deployment_freeze.test_freeze: Creating...
octopusdeploy_deployment_freeze.test_freeze: Creation complete after 0s [id=DeploymentFreezes-814]
```

## Update
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # octopusdeploy_deployment_freeze.test_freeze will be updated in-place
  ~ resource "octopusdeploy_deployment_freeze" "test_freeze" {
        id                 = "DeploymentFreezes-821"
        name               = "Test Recurring Freeze"
      ~ recurring_schedule = {
          ~ days_of_week          = [
              + "Sunday",
                "Monday",
              - "Wednesday",
                "Friday",
            ]
          ~ end_after_occurrences = 5 -> 15
            # (3 unchanged attributes hidden)
        }
        # (2 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

octopusdeploy_deployment_freeze.test_freeze: Modifying... [id=DeploymentFreezes-821]
octopusdeploy_deployment_freeze.test_freeze: Modifications complete after 0s [id=DeploymentFreezes-821]
```
## Destroy
```
  # octopusdeploy_deployment_freeze.test_freeze will be destroyed
  # (because octopusdeploy_deployment_freeze.test_freeze is not in configuration)
  - resource "octopusdeploy_deployment_freeze" "test_freeze" {
      - end                = "2025-12-10T01:47:00Z" -> null
      - id                 = "DeploymentFreezes-821" -> null
      - name               = "Test Recurring Freeze" -> null
      - recurring_schedule = {
          - days_of_week          = [
              - "Sunday",
              - "Monday",
              - "Friday",
            ] -> null
          - end_after_occurrences = 15 -> null
          - end_type              = "AfterOccurrences" -> null
          - type                  = "DaysPerWeek" -> null
          - unit                  = 24 -> null
        } -> null
      - start              = "2025-12-09T01:47:00Z" -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

octopusdeploy_deployment_freeze.test_freeze: Destroying... [id=DeploymentFreezes-821]
octopusdeploy_deployment_freeze.test_freeze: Destruction complete after 0s
```

2024-12-09 06:32 UTC, benPearce1 requested changes
This looks good but adding validation would be ideal.
I got the following error when setting type to `DaysPerMonth` but not setting `monthly_schedule_type`:
```
Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to octopusdeploy_deployment_freeze.freeze, provider "provider[\"octopus.com/com/octopusdeploy\"]" produced an unexpected new value:
│ .recurring_schedule.monthly_schedule_type: was null, but now cty.StringVal("DateOfMonth").
```

2024-12-09 06:32 UTC, benPearce1 commented on octopusdeploy_framework/schemas/deployment_freeze.go
> +					"end_type": resourceSchema.StringAttribute{
We can add validation to some of these fields e.g:
```
Validators: []validator.String{
	stringvalidator.OneOf("Never", "OnDate", "AfterOccurrences"),
},
```

2024-12-09 06:32 UTC, benPearce1 commented on octopusdeploy_framework/schemas/deployment_freeze.go
> +func (v daysOfWeekValidator) ValidateList(ctx context.Context, req validator.ListRequest, resp *validator.ListResponse) {
Might make sense to move this validator to its own file

2024-12-09 07:58 UTC, domenicsim1 approved these changes

2024-12-12 04:18 UTC, domenicsim1 reviewed
Looks, good to me

2024-12-17 04:57 UTC, benPearce1 approved these changes

2024-12-17 23:05 UTC, merged